const otherMsg = {
    "maxLength": 20,
    "minLength": 8,
    "textInput": "text",
    "emailInput": "email",
    "passwordInput": "password",
    "emailTitle": "Email",
    "passwordTitle": "Password",
    "submitType": "submit",
    "buttonType": "button",
    "nameTitle": "Name",
    "nameInput": "userName",
    "fileInput": "file",
    "confirmPasswordInput": "confirmPassword",
    "confirmPasswordTitle": "Confirm Password",
    "contactInput": "contact",
    "contactTitle": "Contact",
    "priceTitle": "Price",
    "priceInput": "price",
    "bookTitle": "Title",
    "bookTitleInput": "title",
    "bookAuthorTitle": "Author",
    "bookAuthorInput": "author",
    "isbnTitle": "ISBN",
    "isbnInput": "isbnCode",
    "pageTitle": "Pages",
    "pageInput": "pages",
    "publishedByTitle": "Published By",
    "publishedByInput": "publishedBy",
    "timeout": 2500,
    "pathToDashboard": "/users/dashboard",
    "pathToHomePage": "/",
    "signupSuccess": "Sign up Complete , wait you are being redirected",
    "loadingMsg": "Loading Please Wait...",
    "customValidator": "password-match",
    "maxPagesAllowed": 7,
    "editBooksPath": "/users/edit-book",
    "contentUnavailable": "Unavailable",
    "actionYes": "Yes",
    "actionNo": "No",
    "editUserPath": "/users/edit-user"

};
export default Object.freeze( otherMsg );