const otherMsg = {
  maxLength: 20,
  minLength: 8,
  textInput: "text",
  emailInput: "email",
  passwordInput: "password",
  emailTitle: "Email",
  passwordTitle: "Password",
  submitType: "submit",
  buttonType: "button",
  nameTitle: "Name",
  nameInput: "userName",
  fileInput: "file",
  confirmPasswordInput: "confirmPassword",
  confirmPasswordTitle: "Confirm Password",
  contactInput: "contact",
  contactTitle: "Contact",
  priceTitle: "Price",
  priceInput: "price",
  bookTitle: "Title",
  bookTitleInput: "title",
  bookAuthorTitle: "Author",
  bookAuthorInput: "author",
  isbnTitle: "ISBN",
  isbnInput: "isbnCode",
  pageTitle: "Pages",
  pageInput: "pages",
  publishedByTitle: "Published By",
  publishedByInput: "publishedBy",
  timeout: 2500,
  pathToDashboard: "/users/dashboard",
  pathToHomePage: "/",
  signupSuccess: "Sign up Complete , wait you are being redirected",
  loadingMsg: "Loading Please Wait...",
  customValidator: "password-match",
  maxPagesAllowed: 7,
  editBooksPath: "/users/edit-book",
  contentUnavailable: "Unavailable",
  actionYes: "Yes",
  actionNo: "No",
  editUserPath: "/users/edit-user",
  dateTimeFormat: "YYYY-MM-DD",
  daysDifference: "days",
  successStatus: "success",
  failedStatus: "failed",
  hotelName: "Name",
  hotelLocation: "Locate On Map",
  landmark: "Landmark",
  hotelType: "Type",
  RoomType: "Room Selected",
  type: "button",
  cardComponentType: "other",
  checkoutImage:
    "https://cdn1.goibibo.com/voy_ing/t_g/81ad700a81ee11e486f9daf4768ad8d9.jfif",
  locationIcon: <i class="fas fa-map-marked-alt"></i>,
  onlineModeOfPayment: "online",
  crossSymbol: " x ",
  indianRuppee: "Rs. ",
  checkoutPath: "/checkout",
  hotelImages: [
    "https://cdn1.goibibo.com/voy_ing/t_g/106925c06e9911e7bdee025f77df004f.jpg",
    "https://cdn1.goibibo.com/voy_ing/t_g/5a89674e15ab11eaa7340242ac110003.jpg",
    "https://cdn1.goibibo.com/voy_ing/t_g/e63a316e83d911ea96850242ac110005.jpg",
    "https://cdn1.goibibo.com/voy_ing/t_g/81ad700a81ee11e486f9daf4768ad8d9.jfif",
  ],
  roomImages: [
    "https://cdn1.goibibo.com/voy_ing/t_fs/7036681c138a11ea9e570242ac110003.jpg",
    "https://cdn1.goibibo.com/voy_ing/t_fs/7067c4c0138a11eaba540242ac110002.jpg",
    "https://cdn1.goibibo.com/voy_ing/t_fs/7070e762138a11eaa6430242ac110004.jpg",
  ],
  hotelPolicies: [
    "It is mandatory for guests to present valid photo identification at the time of check-in.",
    "In case of bookings where payment is charged directly at the resort, we need your Credit Card details to guarantee the booking. The booking confirmation is subject to successful validation of your Credit Card by the resort. Goibibo will not charge your card however, the resort reserves the right to charge a part or full amount before the check-in.",
    "The primary guest checking in to the resort must be at least 18 years of age. If your child requires additional bedding and/or breakfast options, please book them as an adult to ensure the correct room configuration. You will be notified of any additional costs resulting from individual resort policies regarding children staying with parents and age range allowed.",
    "The standard check-in time is 2 PM and the standard check-out time is 12 PM. After booking you will be sent an email confirmation with resort phone number. You can contact the resort directly for early check-in or late check-out. Early check-in or late check-out is subject to availability and may be chargeable by The Tubkaak Krabi Boutique Resort.",
    "The room tariff includes all taxes. The amount paid for the room does not include charges for optional services and facilities (such as room service, mini bar, snacks or telephone calls). These will be charged by the resort at the time of check-out from the resort.",
    "Selective offers of Goibibo will not be valid on cancellation or modification of a booking.",
    "Number of modifications possible on a booking will be on the discretion of Goibibo.",
  ],
  imageAlt: "Not Available",
  pricingInfo: "Pricing Information",
  originalPrice: "Original Price",
  discountPrice: "Discount Price",
  ruppeeIcon: <i class="fas fa-rupee-sign"></i>,
  selectRoom: "Select Room",
  note: "Note : ",
  noteText: "You must Login / signup before Selecting Room",
  roomsNotAvailable: "No rooms Available with such requirements",
  roomsSection: "roomsSection",
  angleIcon: <i class="fas fa-angle-down"></i>,
  soldOut: "Sold Out",
  checkIcon: <i class="fa fa-check-circle" aria-hidden="true"></i>,
  reviewsHeading: "Guest Reviews and Rating",
  roomOptions: "Room Options",
  pricingHeading: "Hotel Pricing and Rooms",
  internetIcon: <i class="fas fa-wifi"></i>,
  internetHeading: " Wifi / Internet ",
  breakfastHeading: " Free Breakfast ",
  breakfastIcon: <i class="fas fa-utensils"></i>,
  hotelIcon: <i class="fas fa-hotel"></i>,
  landmarkIcon: <i class="fas fa-map-marked-alt"></i>,
  overAllRating: "5",
  roomInfo: "Room Information",
  capacity: "Capacity",
  area: "Area",
  bedSize: "Bed Size",
  none: "none",
  searchText: "searchText",
  searchPlaceholder: " Area , Location or Landmark",
  checkIn: "checkIn",
  checkInText: "Check In",
  checkOut: "checkOut",
  checkOutText: "Check OUt",
  dateType: "date",
  standardVariant: "standard",
  block: "block",
  guests: "guests",
  guestText: " Guests In ",
  roomsText: " Room(s)",
  emptyText: "",
  autoComplete: "autocomplete",
  searchType: "search",
  guestInfo: " Guest(s) ",
  addIcon: <i class="fas fa-plus"></i>,
  subtractIcon: <i class="fas fa-minus"></i>,
  childText: "Child ",
  ageText: " Age",
  hotelPolicyHeading: "Hotel Policies",
};
export default Object.freeze(otherMsg);
